/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Interfaz;

import Companies.Company;
import Interfaces.Chart;
import Workers.WorkerTypes;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JProgressBar;

/**
 *
 * @author ani
 */
public class AppleTab extends javax.swing.JPanel {
    
    private Company Apple; 
    
    

    /**
     * Creates new form AppleTab
     */
    public AppleTab(Company Apple) {
        initComponents();
        
        this.Apple = Apple;
       
        //Cantidad de trabajadores
     
        this.apple_cant_placa.setText(Integer.toString(Apple.getEmployees()[0].getSize()));
        this.apple_cant_cpu.setText(Integer.toString(Apple.getEmployees()[1].getSize()));
        this.apple_cant_ram.setText(Integer.toString(Apple.getEmployees()[2].getSize()));
        this.apple_cant_fuentes.setText(Integer.toString(Apple.getEmployees()[3].getSize()));
        this.apple_cant_tarjetas.setText(Integer.toString(Apple.getEmployees()[4].getSize()));
        this.apple_cant_ensambladores.setText(Integer.toString(Apple.getEmployees()[5].getSize()));

        //Condiciones de los progess Bar
        
        this.apple_progressBarPlaca.setMinimum(0);
        this.apple_progressBarPlaca.setMaximum(Apple.getDisk().getMaxMotherboard());
        
        this.apple_progressBarCPU.setMinimum(0);
        this.apple_progressBarCPU.setMaximum(Apple.getDisk().getMaxCpu());
        
        this.apple_progressBarFuente.setMinimum(0);
        this.apple_progressBarFuente.setMaximum(Apple.getDisk().getMaxPowerSupply());
        
        this.apple_progressBarRam.setMinimum(0);
        this.apple_progressBarRam.setMaximum(Apple.getDisk().getMaxRam());
        
        this.apple_progressBarTarjetas.setMinimum(0);
        this.apple_progressBarTarjetas.setMaximum(Apple.getDisk().getMaxGpu());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        appleWindow = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        apple_cant_placa = new javax.swing.JLabel();
        apple_ver_grafico = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        apple_netProfit = new javax.swing.JLabel();
        apple_totalCost = new javax.swing.JLabel();
        apple_totalEarnings = new javax.swing.JLabel();
        apple_mas_placa = new javax.swing.JButton();
        apple_menos_placa = new javax.swing.JButton();
        apple_mas_cpu = new javax.swing.JButton();
        apple_cant_cpu = new javax.swing.JLabel();
        apple_menos_cpu = new javax.swing.JButton();
        apple_mas_ram = new javax.swing.JButton();
        apple_cant_ram = new javax.swing.JLabel();
        apple_menos_ram = new javax.swing.JButton();
        apple_mas_fuentes = new javax.swing.JButton();
        apple_menos_fuentes = new javax.swing.JButton();
        apple_mas_tarjetas = new javax.swing.JButton();
        apple_cant_tarjetas = new javax.swing.JLabel();
        apple_menos_tarjetas = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        apple_progressBarFuente = new javax.swing.JProgressBar();
        apple_mas_ensambladores = new javax.swing.JButton();
        apple_cant_ensambladores = new javax.swing.JLabel();
        apple_menos_ensambladores = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        apple_cant_fuentes = new javax.swing.JLabel();
        apple_gastosTarjeta = new javax.swing.JLabel();
        maxCPU = new javax.swing.JLabel();
        apple_progressBarCPU = new javax.swing.JProgressBar();
        apple_progressBarRam = new javax.swing.JProgressBar();
        maxRAM = new javax.swing.JLabel();
        apple_progressBarPlaca = new javax.swing.JProgressBar();
        maxPlaca = new javax.swing.JLabel();
        apple_progressBarTarjetas = new javax.swing.JProgressBar();
        maxTarjetas = new javax.swing.JLabel();
        numPlacas = new javax.swing.JLabel();
        apple_gastosEnsambladores = new javax.swing.JLabel();
        apple_gastosRAM = new javax.swing.JLabel();
        apple_gastosPlaca = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        apple_gastosCPU = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        apple_dayCounter = new javax.swing.JLabel();
        apple_gastosPM = new javax.swing.JLabel();
        label5 = new javax.swing.JLabel();
        apple_faltasPM = new javax.swing.JLabel();
        apple_gastosDirector = new javax.swing.JLabel();
        apple_gastosFuente = new javax.swing.JLabel();
        label6 = new javax.swing.JLabel();
        apple_salarioDescontado = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        apple_statusDir = new javax.swing.JLabel();
        label20 = new javax.swing.JLabel();
        label21 = new javax.swing.JLabel();
        label22 = new javax.swing.JLabel();
        label2 = new javax.swing.JLabel();
        apple_statusPM = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        apple_compVendidas = new javax.swing.JLabel();
        apple_compTarjeta = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        maxFuente1 = new javax.swing.JLabel();
        numFuente = new javax.swing.JLabel();
        numCPU = new javax.swing.JLabel();
        numRAM = new javax.swing.JLabel();
        numGPU = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();

        appleWindow.setBackground(new java.awt.Color(255, 255, 255));
        appleWindow.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Media/Apple Logo.png"))); // NOI18N
        appleWindow.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 1, 17)); // NOI18N
        jLabel3.setText("Director");
        appleWindow.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 690, -1, -1));

        jSeparator1.setForeground(new java.awt.Color(102, 0, 102));
        appleWindow.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 160, 760, 20));

        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        jLabel4.setText("Productores de Tarjetas Gráficas");
        appleWindow.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 330, 300, -1));

        jLabel6.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        jLabel6.setText("Productores de CPU");
        appleWindow.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 200, -1, -1));

        jLabel7.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        jLabel7.setText("Productores de RAM");
        appleWindow.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 200, -1, -1));

        jLabel8.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        jLabel8.setText("Productores de Placa Base");
        appleWindow.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 330, 220, -1));

        apple_cant_placa.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        apple_cant_placa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        apple_cant_placa.setText("0");
        appleWindow.add(apple_cant_placa, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 360, 30, -1));

        apple_ver_grafico.setBackground(new java.awt.Color(204, 204, 204));
        apple_ver_grafico.setText("Ver Gráfico");
        apple_ver_grafico.setBorderPainted(false);
        apple_ver_grafico.setOpaque(true);
        apple_ver_grafico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apple_ver_graficoActionPerformed(evt);
            }
        });
        appleWindow.add(apple_ver_grafico, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 170, 40));

        jLabel5.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel5.setText("Ganancias:");
        appleWindow.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 100, -1, -1));

        jLabel13.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel13.setText("Gastos totales:");
        appleWindow.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 20, -1, -1));

        jLabel14.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel14.setText("Ingresos totales:");
        appleWindow.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 60, -1, -1));

        apple_netProfit.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        apple_netProfit.setForeground(new java.awt.Color(153, 255, 102));
        apple_netProfit.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        apple_netProfit.setText("0");
        appleWindow.add(apple_netProfit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 100, 120, -1));

        apple_totalCost.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        apple_totalCost.setForeground(new java.awt.Color(255, 51, 51));
        apple_totalCost.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        apple_totalCost.setText("0");
        appleWindow.add(apple_totalCost, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 20, 90, -1));

        apple_totalEarnings.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        apple_totalEarnings.setForeground(new java.awt.Color(153, 255, 102));
        apple_totalEarnings.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        apple_totalEarnings.setText("0");
        appleWindow.add(apple_totalEarnings, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 60, 80, -1));

        apple_mas_placa.setBackground(new java.awt.Color(204, 204, 204));
        apple_mas_placa.setText("+");
        apple_mas_placa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apple_mas_placaActionPerformed(evt);
            }
        });
        appleWindow.add(apple_mas_placa, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 360, 20, -1));

        apple_menos_placa.setBackground(new java.awt.Color(204, 204, 204));
        apple_menos_placa.setText("-");
        apple_menos_placa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apple_menos_placaActionPerformed(evt);
            }
        });
        appleWindow.add(apple_menos_placa, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 360, 20, -1));

        apple_mas_cpu.setBackground(new java.awt.Color(204, 204, 204));
        apple_mas_cpu.setText("+");
        apple_mas_cpu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apple_mas_cpuActionPerformed(evt);
            }
        });
        appleWindow.add(apple_mas_cpu, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 230, 20, -1));

        apple_cant_cpu.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        apple_cant_cpu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        apple_cant_cpu.setText("0");
        appleWindow.add(apple_cant_cpu, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 230, 30, -1));

        apple_menos_cpu.setBackground(new java.awt.Color(204, 204, 204));
        apple_menos_cpu.setText("-");
        apple_menos_cpu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apple_menos_cpuActionPerformed(evt);
            }
        });
        appleWindow.add(apple_menos_cpu, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 230, 20, -1));

        apple_mas_ram.setBackground(new java.awt.Color(204, 204, 204));
        apple_mas_ram.setText("+");
        apple_mas_ram.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apple_mas_ramActionPerformed(evt);
            }
        });
        appleWindow.add(apple_mas_ram, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 230, 20, -1));

        apple_cant_ram.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        apple_cant_ram.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        apple_cant_ram.setText("0");
        appleWindow.add(apple_cant_ram, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 230, 30, -1));

        apple_menos_ram.setBackground(new java.awt.Color(204, 204, 204));
        apple_menos_ram.setText("-");
        apple_menos_ram.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apple_menos_ramActionPerformed(evt);
            }
        });
        appleWindow.add(apple_menos_ram, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 230, 20, -1));

        apple_mas_fuentes.setBackground(new java.awt.Color(204, 204, 204));
        apple_mas_fuentes.setText("+");
        apple_mas_fuentes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apple_mas_fuentesActionPerformed(evt);
            }
        });
        appleWindow.add(apple_mas_fuentes, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 230, 20, -1));

        apple_menos_fuentes.setBackground(new java.awt.Color(204, 204, 204));
        apple_menos_fuentes.setText("-");
        apple_menos_fuentes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apple_menos_fuentesActionPerformed(evt);
            }
        });
        appleWindow.add(apple_menos_fuentes, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 230, 20, -1));

        apple_mas_tarjetas.setBackground(new java.awt.Color(204, 204, 204));
        apple_mas_tarjetas.setText("+");
        apple_mas_tarjetas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apple_mas_tarjetasActionPerformed(evt);
            }
        });
        appleWindow.add(apple_mas_tarjetas, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 360, 20, -1));

        apple_cant_tarjetas.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        apple_cant_tarjetas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        apple_cant_tarjetas.setText("0");
        appleWindow.add(apple_cant_tarjetas, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 360, 30, -1));

        apple_menos_tarjetas.setBackground(new java.awt.Color(204, 204, 204));
        apple_menos_tarjetas.setText("-");
        apple_menos_tarjetas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apple_menos_tarjetasActionPerformed(evt);
            }
        });
        appleWindow.add(apple_menos_tarjetas, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 360, 20, -1));

        jLabel9.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        jLabel9.setText("Manejador de Trabajadores");
        appleWindow.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));
        appleWindow.add(apple_progressBarFuente, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 510, 100, 20));

        apple_mas_ensambladores.setBackground(new java.awt.Color(204, 204, 204));
        apple_mas_ensambladores.setText("+");
        apple_mas_ensambladores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apple_mas_ensambladoresActionPerformed(evt);
            }
        });
        appleWindow.add(apple_mas_ensambladores, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 360, 20, -1));

        apple_cant_ensambladores.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        apple_cant_ensambladores.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        apple_cant_ensambladores.setText("0");
        appleWindow.add(apple_cant_ensambladores, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 360, 30, -1));

        apple_menos_ensambladores.setBackground(new java.awt.Color(204, 204, 204));
        apple_menos_ensambladores.setText("-");
        apple_menos_ensambladores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apple_menos_ensambladoresActionPerformed(evt);
            }
        });
        appleWindow.add(apple_menos_ensambladores, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 360, 20, -1));

        jLabel11.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        jLabel11.setText("Ensambladores");
        appleWindow.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 330, -1, -1));

        jLabel12.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        jLabel12.setText("Placa Base");
        appleWindow.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 510, 200, -1));

        apple_cant_fuentes.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        apple_cant_fuentes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        apple_cant_fuentes.setText("0");
        appleWindow.add(apple_cant_fuentes, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 230, 30, -1));

        apple_gastosTarjeta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        apple_gastosTarjeta.setText("0");
        apple_gastosTarjeta.setToolTipText("");
        appleWindow.add(apple_gastosTarjeta, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 400, 70, -1));

        maxCPU.setText("max. 20");
        appleWindow.add(maxCPU, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 570, 60, -1));
        appleWindow.add(apple_progressBarCPU, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 570, 100, 20));
        appleWindow.add(apple_progressBarRam, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 510, 100, 20));

        maxRAM.setText("max. 55");
        appleWindow.add(maxRAM, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 510, 60, -1));
        appleWindow.add(apple_progressBarPlaca, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 510, 100, 20));

        maxPlaca.setText("max. 25");
        appleWindow.add(maxPlaca, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 510, 60, -1));
        appleWindow.add(apple_progressBarTarjetas, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 570, 100, 20));

        maxTarjetas.setText("max. 10");
        appleWindow.add(maxTarjetas, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 570, 100, -1));

        numPlacas.setText("0");
        appleWindow.add(numPlacas, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 490, 70, -1));

        apple_gastosEnsambladores.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        apple_gastosEnsambladores.setText("0");
        apple_gastosEnsambladores.setToolTipText("");
        appleWindow.add(apple_gastosEnsambladores, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 400, 80, -1));

        apple_gastosRAM.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        apple_gastosRAM.setText("0");
        apple_gastosRAM.setToolTipText("");
        appleWindow.add(apple_gastosRAM, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 270, 70, -1));

        apple_gastosPlaca.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        apple_gastosPlaca.setText("0");
        apple_gastosPlaca.setToolTipText("");
        appleWindow.add(apple_gastosPlaca, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 400, 70, -1));

        jLabel10.setFont(new java.awt.Font("Helvetica Neue", 1, 17)); // NOI18N
        jLabel10.setText("Project Manager");
        appleWindow.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 650, -1, -1));

        apple_gastosCPU.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        apple_gastosCPU.setText("0");
        apple_gastosCPU.setToolTipText("");
        appleWindow.add(apple_gastosCPU, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 270, 70, -1));

        jLabel15.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel15.setText("Day Counter");
        appleWindow.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 40, -1, -1));

        apple_dayCounter.setFont(new java.awt.Font("Helvetica Neue", 0, 36)); // NOI18N
        apple_dayCounter.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        apple_dayCounter.setText("0");
        appleWindow.add(apple_dayCounter, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 80, 90, -1));

        apple_gastosPM.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        apple_gastosPM.setText("0 $");
        appleWindow.add(apple_gastosPM, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 650, 90, -1));

        label5.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        label5.setText("Faltas");
        appleWindow.add(label5, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 650, 50, -1));

        apple_faltasPM.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        apple_faltasPM.setText("0");
        appleWindow.add(apple_faltasPM, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 650, 40, -1));

        apple_gastosDirector.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        apple_gastosDirector.setText("0 $");
        appleWindow.add(apple_gastosDirector, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 690, 90, -1));

        apple_gastosFuente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        apple_gastosFuente.setText("0");
        apple_gastosFuente.setToolTipText("");
        appleWindow.add(apple_gastosFuente, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 270, 70, -1));

        label6.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        label6.setText("Descontado");
        appleWindow.add(label6, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 650, 90, -1));

        apple_salarioDescontado.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        apple_salarioDescontado.setText("0 $");
        appleWindow.add(apple_salarioDescontado, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 650, 80, -1));

        jLabel16.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        jLabel16.setText("Productores de Fuente de Alimentación");
        appleWindow.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, 310, -1));

        jSeparator2.setForeground(new java.awt.Color(102, 0, 102));
        appleWindow.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 610, 1100, 20));

        jLabel17.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        jLabel17.setText("Almacenamiento");
        appleWindow.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, -1, -1));

        jLabel18.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        jLabel18.setText("Fuente de Alimentación");
        appleWindow.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 510, 200, -1));

        jLabel19.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        jLabel19.setText("CPU");
        appleWindow.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 570, 200, -1));

        jLabel20.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        jLabel20.setText("RAM");
        appleWindow.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 510, 200, -1));

        jLabel21.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        jLabel21.setText("Tarjetas Gráficas");
        appleWindow.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 570, 200, -1));

        jSeparator3.setForeground(new java.awt.Color(102, 0, 102));
        appleWindow.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 460, 890, 20));

        apple_statusDir.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        apple_statusDir.setText("\"\"");
        appleWindow.add(apple_statusDir, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 690, 120, -1));

        label20.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        label20.setText("Salario");
        appleWindow.add(label20, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 650, 60, -1));

        label21.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        label21.setText("Estatus:");
        appleWindow.add(label21, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 690, 60, -1));

        label22.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        label22.setText("Salario");
        appleWindow.add(label22, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 690, 60, -1));

        label2.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        label2.setText("Estatus:");
        appleWindow.add(label2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 650, 70, -1));

        apple_statusPM.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        apple_statusPM.setText("\"\"");
        appleWindow.add(apple_statusPM, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 650, 120, -1));

        jLabel22.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel22.setText("Regulares");
        appleWindow.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 50, 100, -1));

        apple_compVendidas.setFont(new java.awt.Font("Helvetica Neue", 0, 36)); // NOI18N
        apple_compVendidas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        apple_compVendidas.setText("0");
        appleWindow.add(apple_compVendidas, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 80, 150, -1));

        apple_compTarjeta.setFont(new java.awt.Font("Helvetica Neue", 0, 36)); // NOI18N
        apple_compTarjeta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        apple_compTarjeta.setText("0");
        appleWindow.add(apple_compTarjeta, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 80, 130, -1));

        jLabel24.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel24.setText("Computadoras");
        appleWindow.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 30, 140, -1));

        jLabel25.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel25.setText("Computadoras");
        appleWindow.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 30, 140, -1));

        jLabel26.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel26.setText("Tarjeta Gráfica");
        appleWindow.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 50, 140, -1));

        maxFuente1.setText("max. 35");
        appleWindow.add(maxFuente1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 510, 70, -1));

        numFuente.setText("0");
        appleWindow.add(numFuente, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 490, 70, -1));

        numCPU.setText("0");
        appleWindow.add(numCPU, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 550, 70, -1));

        numRAM.setText("0");
        appleWindow.add(numRAM, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 490, 70, -1));

        numGPU.setText("0");
        appleWindow.add(numGPU, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 550, 70, -1));

        jLabel1.setText("Gastos:");
        appleWindow.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 400, -1, -1));

        jLabel23.setText("Gastos:");
        appleWindow.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 270, -1, -1));

        jLabel27.setText("Gastos:");
        appleWindow.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 270, -1, -1));

        jLabel28.setText("Gastos:");
        appleWindow.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, -1, -1));

        jLabel29.setText("Gastos:");
        appleWindow.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 400, -1, -1));

        jLabel30.setText("Gastos:");
        appleWindow.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 400, -1, -1));

        jLabel31.setText("$");
        appleWindow.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 400, -1, -1));

        jLabel32.setText("$");
        appleWindow.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 270, -1, -1));

        jLabel33.setText("$");
        appleWindow.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 400, -1, -1));

        jLabel34.setText("$");
        appleWindow.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 400, -1, -1));

        jLabel35.setText("$");
        appleWindow.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 270, -1, -1));

        jLabel36.setText("$");
        appleWindow.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 270, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1226, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(appleWindow, javax.swing.GroupLayout.PREFERRED_SIZE, 1226, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 782, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(appleWindow, javax.swing.GroupLayout.PREFERRED_SIZE, 782, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void apple_ver_graficoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apple_ver_graficoActionPerformed
        Chart appleChart = new Chart(this.getApple(), 0, null);
    }//GEN-LAST:event_apple_ver_graficoActionPerformed

    private void apple_mas_fuentesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apple_mas_fuentesActionPerformed
        // TODO add your handling code here:
        getApple().hireEmployee(WorkerTypes.PowerSupplyProducer.getId());
        this.getApple_cant_fuentes().setText(Integer.toString(getApple().getEmployees()[WorkerTypes.PowerSupplyProducer.getId()].getSize()));
    }//GEN-LAST:event_apple_mas_fuentesActionPerformed

    private void apple_menos_fuentesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apple_menos_fuentesActionPerformed
        // TODO add your handling code here:
        getApple().fireEmployee(WorkerTypes.PowerSupplyProducer.getId());
        this.getApple_cant_fuentes().setText(Integer.toString(getApple().getEmployees()[WorkerTypes.PowerSupplyProducer.getId()].getSize()));        
    }//GEN-LAST:event_apple_menos_fuentesActionPerformed

    private void apple_menos_cpuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apple_menos_cpuActionPerformed
        // TODO add your handling code here:
        getApple().fireEmployee(WorkerTypes.CpuProducer.getId());
        this.getApple_cant_cpu().setText(Integer.toString(getApple().getEmployees()[WorkerTypes.CpuProducer.getId()].getSize()));        
    }//GEN-LAST:event_apple_menos_cpuActionPerformed

    private void apple_mas_cpuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apple_mas_cpuActionPerformed
        // TODO add your handling code here:
        getApple().hireEmployee(WorkerTypes.CpuProducer.getId());
        this.getApple_cant_cpu().setText(Integer.toString(getApple().getEmployees()[WorkerTypes.CpuProducer.getId()].getSize()));
    }//GEN-LAST:event_apple_mas_cpuActionPerformed

    private void apple_menos_ramActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apple_menos_ramActionPerformed
        // TODO add your handling code here:
        getApple().fireEmployee(WorkerTypes.RamProducer.getId());
        this.getApple_cant_ram().setText(Integer.toString(getApple().getEmployees()[WorkerTypes.RamProducer.getId()].getSize()));        
    }//GEN-LAST:event_apple_menos_ramActionPerformed

    private void apple_mas_ramActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apple_mas_ramActionPerformed
        // TODO add your handling code here:
        getApple().hireEmployee(WorkerTypes.RamProducer.getId());
        this.getApple_cant_ram().setText(Integer.toString(getApple().getEmployees()[WorkerTypes.RamProducer.getId()].getSize()));
    }//GEN-LAST:event_apple_mas_ramActionPerformed

    private void apple_menos_tarjetasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apple_menos_tarjetasActionPerformed
        // TODO add your handling code here:
        getApple().fireEmployee(WorkerTypes.GpuProducer.getId());
        this.getApple_cant_tarjetas().setText(Integer.toString(getApple().getEmployees()[WorkerTypes.GpuProducer.getId()].getSize()));        
    }//GEN-LAST:event_apple_menos_tarjetasActionPerformed

    private void apple_mas_tarjetasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apple_mas_tarjetasActionPerformed
        // TODO add your handling code here:
        getApple().hireEmployee(WorkerTypes.GpuProducer.getId());
        this.getApple_cant_tarjetas().setText(Integer.toString(getApple().getEmployees()[WorkerTypes.GpuProducer.getId()].getSize()));
    }//GEN-LAST:event_apple_mas_tarjetasActionPerformed

    private void apple_menos_placaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apple_menos_placaActionPerformed
        // TODO add your handling code here:
        getApple().fireEmployee(WorkerTypes.MotherboardProducer.getId());
        this.getApple_cant_placa().setText(Integer.toString(getApple().getEmployees()[WorkerTypes.MotherboardProducer.getId()].getSize()));        
    }//GEN-LAST:event_apple_menos_placaActionPerformed

    private void apple_mas_placaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apple_mas_placaActionPerformed
        // TODO add your handling code here:
        getApple().hireEmployee(WorkerTypes.MotherboardProducer.getId());
        this.getApple_cant_placa().setText(Integer.toString(getApple().getEmployees()[WorkerTypes.MotherboardProducer.getId()].getSize()));
    }//GEN-LAST:event_apple_mas_placaActionPerformed

    private void apple_menos_ensambladoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apple_menos_ensambladoresActionPerformed
        // TODO add your handling code here:
        getApple().fireEmployee(WorkerTypes.Assembler.getId());
        this.getApple_cant_ensambladores().setText(Integer.toString(getApple().getEmployees()[WorkerTypes.Assembler.getId()].getSize()));        
    }//GEN-LAST:event_apple_menos_ensambladoresActionPerformed

    private void apple_mas_ensambladoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apple_mas_ensambladoresActionPerformed
        // TODO add your handling code here:
        getApple().hireEmployee(WorkerTypes.Assembler.getId());
        this.getApple_cant_ensambladores().setText(Integer.toString(getApple().getEmployees()[WorkerTypes.Assembler.getId()].getSize()));
    }//GEN-LAST:event_apple_mas_ensambladoresActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel appleWindow;
    private javax.swing.JLabel apple_cant_cpu;
    private javax.swing.JLabel apple_cant_ensambladores;
    private javax.swing.JLabel apple_cant_fuentes;
    private javax.swing.JLabel apple_cant_placa;
    private javax.swing.JLabel apple_cant_ram;
    private javax.swing.JLabel apple_cant_tarjetas;
    private javax.swing.JLabel apple_compTarjeta;
    private javax.swing.JLabel apple_compVendidas;
    private javax.swing.JLabel apple_dayCounter;
    private javax.swing.JLabel apple_faltasPM;
    private javax.swing.JLabel apple_gastosCPU;
    private javax.swing.JLabel apple_gastosDirector;
    private javax.swing.JLabel apple_gastosEnsambladores;
    private javax.swing.JLabel apple_gastosFuente;
    private javax.swing.JLabel apple_gastosPM;
    private javax.swing.JLabel apple_gastosPlaca;
    private javax.swing.JLabel apple_gastosRAM;
    private javax.swing.JLabel apple_gastosTarjeta;
    private javax.swing.JButton apple_mas_cpu;
    private javax.swing.JButton apple_mas_ensambladores;
    private javax.swing.JButton apple_mas_fuentes;
    private javax.swing.JButton apple_mas_placa;
    private javax.swing.JButton apple_mas_ram;
    private javax.swing.JButton apple_mas_tarjetas;
    private javax.swing.JButton apple_menos_cpu;
    private javax.swing.JButton apple_menos_ensambladores;
    private javax.swing.JButton apple_menos_fuentes;
    private javax.swing.JButton apple_menos_placa;
    private javax.swing.JButton apple_menos_ram;
    private javax.swing.JButton apple_menos_tarjetas;
    private javax.swing.JLabel apple_netProfit;
    private javax.swing.JProgressBar apple_progressBarCPU;
    private javax.swing.JProgressBar apple_progressBarFuente;
    private javax.swing.JProgressBar apple_progressBarPlaca;
    private javax.swing.JProgressBar apple_progressBarRam;
    private javax.swing.JProgressBar apple_progressBarTarjetas;
    private javax.swing.JLabel apple_salarioDescontado;
    private javax.swing.JLabel apple_statusDir;
    private javax.swing.JLabel apple_statusPM;
    private javax.swing.JLabel apple_totalCost;
    private javax.swing.JLabel apple_totalEarnings;
    private javax.swing.JButton apple_ver_grafico;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel label2;
    private javax.swing.JLabel label20;
    private javax.swing.JLabel label21;
    private javax.swing.JLabel label22;
    private javax.swing.JLabel label5;
    private javax.swing.JLabel label6;
    private javax.swing.JLabel maxCPU;
    private javax.swing.JLabel maxFuente1;
    private javax.swing.JLabel maxPlaca;
    private javax.swing.JLabel maxRAM;
    private javax.swing.JLabel maxTarjetas;
    private javax.swing.JLabel numCPU;
    private javax.swing.JLabel numFuente;
    private javax.swing.JLabel numGPU;
    private javax.swing.JLabel numPlacas;
    private javax.swing.JLabel numRAM;
    // End of variables declaration//GEN-END:variables

    public Company getApple() {
        return Apple;
    }

    public void setDell(Company Apple) {
        this.Apple = Apple;
    }

    public JLabel getApple_cant_cpu() {
        return apple_cant_cpu;
    }

    public void setApple_cant_cpu(JLabel apple_cant_cpu) {
        this.apple_cant_cpu = apple_cant_cpu;
    }

    public JLabel getApple_cant_ensambladores() {
        return apple_cant_ensambladores;
    }

    public void setApple_cant_ensambladores(JLabel apple_cant_ensambladores) {
        this.apple_cant_ensambladores = apple_cant_ensambladores;
    }

    public JLabel getApple_cant_fuentes() {
        return apple_cant_fuentes;
    }

    public void setApple_cant_fuentes(JLabel apple_cant_fuentes) {
        this.apple_cant_fuentes = apple_cant_fuentes;
    }

    public JLabel getApple_cant_placa() {
        return apple_cant_placa;
    }

    public void setApple_cant_placa(JLabel apple_cant_placa) {
        this.apple_cant_placa = apple_cant_placa;
    }

    public JLabel getApple_cant_ram() {
        return apple_cant_ram;
    }

    public void setApple_cant_ram(JLabel apple_cant_ram) {
        this.apple_cant_ram = apple_cant_ram;
    }

    public JLabel getApple_cant_tarjetas() {
        return apple_cant_tarjetas;
    }

    public void setApple_cant_tarjetas(JLabel apple_cant_tarjetas) {
        this.apple_cant_tarjetas = apple_cant_tarjetas;
    }

    public JLabel getApple_compTarjeta() {
        return apple_compTarjeta;
    }

    public void setApple_compTarjeta(JLabel apple_compTarjeta) {
        this.apple_compTarjeta = apple_compTarjeta;
    }

    public JLabel getApple_compVendidas() {
        return apple_compVendidas;
    }

    public void setApple_compVendidas(JLabel apple_compVendidas) {
        this.apple_compVendidas = apple_compVendidas;
    }

    public JLabel getApple_dayCounter() {
        return apple_dayCounter;
    }

    public void setApple_dayCounter(JLabel apple_dayCounter) {
        this.apple_dayCounter = apple_dayCounter;
    }

    public JLabel getApple_faltasPM() {
        return apple_faltasPM;
    }

    public void setApple_faltasPM(JLabel apple_faltasPM) {
        this.apple_faltasPM = apple_faltasPM;
    }

    public JLabel getApple_gastosCPU() {
        return apple_gastosCPU;
    }

    public void setApple_gastosCPU(JLabel apple_gastosCPU) {
        this.apple_gastosCPU = apple_gastosCPU;
    }

    public JLabel getApple_gastosDirector() {
        return apple_gastosDirector;
    }

    public void setApple_gastosDirector(JLabel apple_gastosDirector) {
        this.apple_gastosDirector = apple_gastosDirector;
    }

    public JLabel getApple_gastosEnsambladores() {
        return apple_gastosEnsambladores;
    }

    public void setApple_gastosEnsambladores(JLabel apple_gastosEnsambladores) {
        this.apple_gastosEnsambladores = apple_gastosEnsambladores;
    }

    public JLabel getApple_gastosFuente() {
        return apple_gastosFuente;
    }

    public void setApple_gastosFuente(JLabel apple_gastosFuente) {
        this.apple_gastosFuente = apple_gastosFuente;
    }

    public JLabel getApple_gastosPM() {
        return apple_gastosPM;
    }

    public void setApple_gastosPM(JLabel apple_gastosPM) {
        this.apple_gastosPM = apple_gastosPM;
    }

    public JLabel getApple_gastosPlaca() {
        return apple_gastosPlaca;
    }

    public void setApple_gastosPlaca(JLabel apple_gastosPlaca) {
        this.apple_gastosPlaca = apple_gastosPlaca;
    }

    public JLabel getApple_gastosRAM() {
        return apple_gastosRAM;
    }

    public void setApple_gastosRAM(JLabel apple_gastosRAM) {
        this.apple_gastosRAM = apple_gastosRAM;
    }

    public JLabel getApple_gastosTarjeta() {
        return apple_gastosTarjeta;
    }

    public void setApple_gastosTarjeta(JLabel apple_gastosTarjeta) {
        this.apple_gastosTarjeta = apple_gastosTarjeta;
    }

    public JLabel getApple_netProfit() {
        return apple_netProfit;
    }

    public void setApple_netProfit(JLabel apple_netProfit) {
        this.apple_netProfit = apple_netProfit;
    }

    public JProgressBar getApple_progressBarCPU() {
        return apple_progressBarCPU;
    }

    public void setApple_progressBarCPU(JProgressBar apple_progressBarCPU) {
        this.apple_progressBarCPU = apple_progressBarCPU;
    }

    public JProgressBar getApple_progressBarFuente() {
        return apple_progressBarFuente;
    }

    public void setApple_progressBarFuente(JProgressBar apple_progressBarFuente) {
        this.apple_progressBarFuente = apple_progressBarFuente;
    }

    public JProgressBar getApple_progressBarPlaca() {
        return apple_progressBarPlaca;
    }

    public void setApple_progressBarPlaca(JProgressBar apple_progressBarPlaca) {
        this.apple_progressBarPlaca = apple_progressBarPlaca;
    }

    public JProgressBar getApple_progressBarRam() {
        return apple_progressBarRam;
    }

    public void setApple_progressBarRam(JProgressBar apple_progressBarRam) {
        this.apple_progressBarRam = apple_progressBarRam;
    }

    public JProgressBar getApple_progressBarTarjetas() {
        return apple_progressBarTarjetas;
    }

    public void setApple_progressBarTarjetas(JProgressBar apple_progressBarTarjetas) {
        this.apple_progressBarTarjetas = apple_progressBarTarjetas;
    }

    public JLabel getApple_salarioDescontado() {
        return apple_salarioDescontado;
    }

    public void setApple_salarioDescontado(JLabel apple_salarioDescontado) {
        this.apple_salarioDescontado = apple_salarioDescontado;
    }

    public JLabel getApple_statusDir() {
        return apple_statusDir;
    }

    public void setApple_statusDir(JLabel apple_statusDir) {
        this.apple_statusDir = apple_statusDir;
    }

    public JLabel getApple_statusPM() {
        return apple_statusPM;
    }

    public void setApple_statusPM(JLabel apple_statusPM) {
        this.apple_statusPM = apple_statusPM;
    }

    public JLabel getApple_totalCost() {
        return apple_totalCost;
    }

    public void setApple_totalCost(JLabel apple_totalCost) {
        this.apple_totalCost = apple_totalCost;
    }

    public JLabel getApple_totalEarnings() {
        return apple_totalEarnings;
    }

    public void setApple_totalEarnings(JLabel apple_totalEarnings) {
        this.apple_totalEarnings = apple_totalEarnings;
    }

    public JButton getApple_ver_grafico() {
        return apple_ver_grafico;
    }

    public void setApple_ver_grafico(JButton apple_ver_grafico) {
        this.apple_ver_grafico = apple_ver_grafico;
    }

    public JLabel getMaxCPU() {
        return maxCPU;
    }

    public void setMaxCPU(JLabel maxCPU) {
        this.maxCPU = maxCPU;
    }

    public JLabel getMaxFuente1() {
        return maxFuente1;
    }

    public void setMaxFuente1(JLabel maxFuente1) {
        this.maxFuente1 = maxFuente1;
    }

    public JLabel getMaxPlaca() {
        return maxPlaca;
    }

    public void setMaxPlaca(JLabel maxPlaca) {
        this.maxPlaca = maxPlaca;
    }

    public JLabel getMaxRAM() {
        return maxRAM;
    }

    public void setMaxRAM(JLabel maxRAM) {
        this.maxRAM = maxRAM;
    }

    public JLabel getMaxTarjetas() {
        return maxTarjetas;
    }

    public void setMaxTarjetas(JLabel maxTarjetas) {
        this.maxTarjetas = maxTarjetas;
    }

    public JLabel getNumCPU() {
        return numCPU;
    }

    public void setNumCPU(JLabel numCPU) {
        this.numCPU = numCPU;
    }

    public JLabel getNumFuente() {
        return numFuente;
    }

    public void setNumFuente(JLabel numFuente) {
        this.numFuente = numFuente;
    }

    public JLabel getNumGPU() {
        return numGPU;
    }

    public void setNumGPU(JLabel numGPU) {
        this.numGPU = numGPU;
    }

    public JLabel getNumPlacas() {
        return numPlacas;
    }

    public void setNumPlacas(JLabel numPlacas) {
        this.numPlacas = numPlacas;
    }

    public JLabel getNumRAM() {
        return numRAM;
    }

    public void setNumRAM(JLabel numRAM) {
        this.numRAM = numRAM;
    }
    
    

}













