/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Interfaz;

import Companies.Company;
import static Main.CommonVariables.getDell;
import Workers.WorkerTypes;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JProgressBar;

/**
 *
 * @author ani
 */
public class DellTab extends javax.swing.JPanel {
    
    private Company Dell;
    
    public DellTab(Company dell) {
        initComponents();
        
        
        this.Dell = dell;
       
        
        //Cantidad de trabajadores
     
        this.dell_cant_placa.setText(Integer.toString(dell.getEmployees()[0].getSize()));
        this.dell_cant_cpu.setText(Integer.toString(dell.getEmployees()[1].getSize()));
        this.dell_cant_ram.setText(Integer.toString(dell.getEmployees()[2].getSize()));
        this.dell_cant_fuentes.setText(Integer.toString(dell.getEmployees()[3].getSize()));
        this.dell_cant_tarjetas.setText(Integer.toString(dell.getEmployees()[4].getSize()));
        this.dell_cant_ensambladores.setText(Integer.toString(dell.getEmployees()[5].getSize()));

        //Condiciones de los progess Bar
        
        this.dell_progressBarPlaca.setMinimum(0);
        this.dell_progressBarPlaca.setMaximum(dell.getDisk().getMaxMotherboard());
        
        this.dell_progressBarCPU.setMinimum(0);
        this.dell_progressBarCPU.setMaximum(dell.getDisk().getMaxCpu());
        
        this.dell_progressBarFuente.setMinimum(0);
        this.dell_progressBarFuente.setMaximum(dell.getDisk().getMaxPowerSupply());
        
        this.dell_progressBarRam.setMinimum(0);
        this.dell_progressBarRam.setMaximum(dell.getDisk().getMaxRam());
        
        this.dell_progressBarTarjetas.setMinimum(0);
        this.dell_progressBarTarjetas.setMaximum(dell.getDisk().getMaxGpu());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        dellWindow = new javax.swing.JPanel();
        dell_inicio_simulacion = new javax.swing.JButton();
        jLabel51 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        dell_cant_placa = new javax.swing.JLabel();
        dell_ver_grafico = new javax.swing.JButton();
        jLabel56 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        dell_netProfit = new javax.swing.JLabel();
        dell_totalCost = new javax.swing.JLabel();
        dell_totalEarnings = new javax.swing.JLabel();
        dell_mas_placa = new javax.swing.JButton();
        dell_menos_placa = new javax.swing.JButton();
        dell_mas_cpu = new javax.swing.JButton();
        dell_cant_cpu = new javax.swing.JLabel();
        dell_menos_cpu = new javax.swing.JButton();
        dell_mas_ram = new javax.swing.JButton();
        dell_cant_ram = new javax.swing.JLabel();
        dell_menos_ram = new javax.swing.JButton();
        dell_mas_fuentes = new javax.swing.JButton();
        dell_menos_fuentes = new javax.swing.JButton();
        dell_mas_tarjetas = new javax.swing.JButton();
        dell_cant_tarjetas = new javax.swing.JLabel();
        dell_menos_tarjetas = new javax.swing.JButton();
        jLabel59 = new javax.swing.JLabel();
        dell_progressBarFuente = new javax.swing.JProgressBar();
        dell_mas_ensambladores = new javax.swing.JButton();
        dell_cant_ensambladores = new javax.swing.JLabel();
        dell_menos_ensambladores = new javax.swing.JButton();
        jLabel60 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        dell_cant_fuentes = new javax.swing.JLabel();
        dell_gastosTarjeta = new javax.swing.JLabel();
        maxCPU2 = new javax.swing.JLabel();
        dell_progressBarCPU = new javax.swing.JProgressBar();
        dell_progressBarRam = new javax.swing.JProgressBar();
        maxRAM2 = new javax.swing.JLabel();
        dell_progressBarPlaca = new javax.swing.JProgressBar();
        maxPlaca2 = new javax.swing.JLabel();
        dell_progressBarTarjetas = new javax.swing.JProgressBar();
        maxTarjetas2 = new javax.swing.JLabel();
        numGPU = new javax.swing.JLabel();
        dell_gastosEnsambladores = new javax.swing.JLabel();
        dell_gastosRAM = new javax.swing.JLabel();
        dell_gastosPlaca = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        dell_gastosCPU = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        dell_dayCounter = new javax.swing.JLabel();
        dell_gastosPM = new javax.swing.JLabel();
        label11 = new javax.swing.JLabel();
        dell_faltasPM = new javax.swing.JLabel();
        dell_gastosDirector = new javax.swing.JLabel();
        dell_gastosFuente = new javax.swing.JLabel();
        label12 = new javax.swing.JLabel();
        dell_salarioDescontado = new javax.swing.JLabel();
        jLabel64 = new javax.swing.JLabel();
        jSeparator8 = new javax.swing.JSeparator();
        jLabel65 = new javax.swing.JLabel();
        jLabel66 = new javax.swing.JLabel();
        jLabel67 = new javax.swing.JLabel();
        jLabel68 = new javax.swing.JLabel();
        jLabel69 = new javax.swing.JLabel();
        jSeparator9 = new javax.swing.JSeparator();
        dell_statusDir = new javax.swing.JLabel();
        label26 = new javax.swing.JLabel();
        label27 = new javax.swing.JLabel();
        label28 = new javax.swing.JLabel();
        label14 = new javax.swing.JLabel();
        dell_statusPM = new javax.swing.JLabel();
        jLabel70 = new javax.swing.JLabel();
        dell_compVendidas = new javax.swing.JLabel();
        dell_compTarjeta = new javax.swing.JLabel();
        jLabel71 = new javax.swing.JLabel();
        jLabel72 = new javax.swing.JLabel();
        jLabel73 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        maxFuente3 = new javax.swing.JLabel();
        numFuentes = new javax.swing.JLabel();
        numCPU = new javax.swing.JLabel();
        numPlaca = new javax.swing.JLabel();
        numRAM = new javax.swing.JLabel();

        dellWindow.setBackground(new java.awt.Color(0, 0, 102));
        dellWindow.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dell_inicio_simulacion.setText("Iniciar Simulación");
        dell_inicio_simulacion.setBorderPainted(false);
        dell_inicio_simulacion.setOpaque(true);
        dell_inicio_simulacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dell_inicio_simulacionActionPerformed(evt);
            }
        });
        dellWindow.add(dell_inicio_simulacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, 170, 40));

        jLabel51.setFont(new java.awt.Font("Helvetica Neue", 1, 17)); // NOI18N
        jLabel51.setForeground(new java.awt.Color(255, 255, 255));
        jLabel51.setText("Director");
        dellWindow.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 690, -1, -1));

        jSeparator7.setForeground(new java.awt.Color(255, 255, 255));
        dellWindow.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 160, 760, 20));

        jLabel52.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        jLabel52.setForeground(new java.awt.Color(255, 255, 255));
        jLabel52.setText("Productores de Tarjetas Gráficas");
        dellWindow.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 330, 300, -1));

        jLabel53.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        jLabel53.setForeground(new java.awt.Color(255, 255, 255));
        jLabel53.setText("Productores de CPU");
        dellWindow.add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 200, -1, -1));

        jLabel54.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        jLabel54.setForeground(new java.awt.Color(255, 255, 255));
        jLabel54.setText("Productores de RAM");
        dellWindow.add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 200, -1, -1));

        jLabel55.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        jLabel55.setForeground(new java.awt.Color(255, 255, 255));
        jLabel55.setText("Productores de Placa Base");
        dellWindow.add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 330, 220, -1));

        dell_cant_placa.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        dell_cant_placa.setForeground(new java.awt.Color(255, 255, 255));
        dell_cant_placa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dell_cant_placa.setText("0");
        dellWindow.add(dell_cant_placa, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 360, 30, -1));

        dell_ver_grafico.setText("Ver Gráfico");
        dell_ver_grafico.setBorderPainted(false);
        dell_ver_grafico.setOpaque(true);
        dell_ver_grafico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dell_ver_graficoActionPerformed(evt);
            }
        });
        dellWindow.add(dell_ver_grafico, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 170, 40));

        jLabel56.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel56.setForeground(new java.awt.Color(255, 255, 255));
        jLabel56.setText("Ganancias:");
        dellWindow.add(jLabel56, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 100, -1, -1));

        jLabel57.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel57.setForeground(new java.awt.Color(255, 255, 255));
        jLabel57.setText("Gastos totales:");
        dellWindow.add(jLabel57, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 20, -1, -1));

        jLabel58.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel58.setForeground(new java.awt.Color(255, 255, 255));
        jLabel58.setText("Ingresos totales:");
        dellWindow.add(jLabel58, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 60, -1, -1));

        dell_netProfit.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        dell_netProfit.setForeground(new java.awt.Color(153, 255, 102));
        dell_netProfit.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        dell_netProfit.setText("0");
        dellWindow.add(dell_netProfit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 100, 120, -1));

        dell_totalCost.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        dell_totalCost.setForeground(new java.awt.Color(255, 51, 51));
        dell_totalCost.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        dell_totalCost.setText("0");
        dellWindow.add(dell_totalCost, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 20, 90, -1));

        dell_totalEarnings.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        dell_totalEarnings.setForeground(new java.awt.Color(153, 255, 102));
        dell_totalEarnings.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        dell_totalEarnings.setText("0");
        dellWindow.add(dell_totalEarnings, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 60, 80, -1));

        dell_mas_placa.setBackground(new java.awt.Color(204, 204, 204));
        dell_mas_placa.setText("+");
        dell_mas_placa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dell_mas_placaActionPerformed(evt);
            }
        });
        dellWindow.add(dell_mas_placa, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 360, 20, -1));

        dell_menos_placa.setBackground(new java.awt.Color(204, 204, 204));
        dell_menos_placa.setText("-");
        dell_menos_placa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dell_menos_placaActionPerformed(evt);
            }
        });
        dellWindow.add(dell_menos_placa, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 360, 20, -1));

        dell_mas_cpu.setBackground(new java.awt.Color(204, 204, 204));
        dell_mas_cpu.setText("+");
        dell_mas_cpu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dell_mas_cpuActionPerformed(evt);
            }
        });
        dellWindow.add(dell_mas_cpu, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 230, 20, -1));

        dell_cant_cpu.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        dell_cant_cpu.setForeground(new java.awt.Color(255, 255, 255));
        dell_cant_cpu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dell_cant_cpu.setText("0");
        dellWindow.add(dell_cant_cpu, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 230, 30, -1));

        dell_menos_cpu.setBackground(new java.awt.Color(204, 204, 204));
        dell_menos_cpu.setText("-");
        dell_menos_cpu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dell_menos_cpuActionPerformed(evt);
            }
        });
        dellWindow.add(dell_menos_cpu, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 230, 20, -1));

        dell_mas_ram.setBackground(new java.awt.Color(204, 204, 204));
        dell_mas_ram.setText("+");
        dell_mas_ram.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dell_mas_ramActionPerformed(evt);
            }
        });
        dellWindow.add(dell_mas_ram, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 230, 20, -1));

        dell_cant_ram.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        dell_cant_ram.setForeground(new java.awt.Color(255, 255, 255));
        dell_cant_ram.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dell_cant_ram.setText("0");
        dellWindow.add(dell_cant_ram, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 230, 30, -1));

        dell_menos_ram.setBackground(new java.awt.Color(204, 204, 204));
        dell_menos_ram.setText("-");
        dell_menos_ram.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dell_menos_ramActionPerformed(evt);
            }
        });
        dellWindow.add(dell_menos_ram, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 230, 20, -1));

        dell_mas_fuentes.setBackground(new java.awt.Color(204, 204, 204));
        dell_mas_fuentes.setText("+");
        dell_mas_fuentes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dell_mas_fuentesActionPerformed(evt);
            }
        });
        dellWindow.add(dell_mas_fuentes, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 230, 20, -1));

        dell_menos_fuentes.setBackground(new java.awt.Color(204, 204, 204));
        dell_menos_fuentes.setText("-");
        dell_menos_fuentes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dell_menos_fuentesActionPerformed(evt);
            }
        });
        dellWindow.add(dell_menos_fuentes, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 230, 20, -1));

        dell_mas_tarjetas.setBackground(new java.awt.Color(204, 204, 204));
        dell_mas_tarjetas.setText("+");
        dell_mas_tarjetas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dell_mas_tarjetasActionPerformed(evt);
            }
        });
        dellWindow.add(dell_mas_tarjetas, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 360, 20, -1));

        dell_cant_tarjetas.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        dell_cant_tarjetas.setForeground(new java.awt.Color(255, 255, 255));
        dell_cant_tarjetas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dell_cant_tarjetas.setText("0");
        dellWindow.add(dell_cant_tarjetas, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 360, 30, -1));

        dell_menos_tarjetas.setBackground(new java.awt.Color(204, 204, 204));
        dell_menos_tarjetas.setText("-");
        dell_menos_tarjetas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dell_menos_tarjetasActionPerformed(evt);
            }
        });
        dellWindow.add(dell_menos_tarjetas, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 360, 20, -1));

        jLabel59.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        jLabel59.setForeground(new java.awt.Color(255, 255, 255));
        jLabel59.setText("Manejador de Trabajadores");
        dellWindow.add(jLabel59, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        dell_progressBarFuente.setForeground(new java.awt.Color(255, 255, 255));
        dellWindow.add(dell_progressBarFuente, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 510, 100, 20));

        dell_mas_ensambladores.setBackground(new java.awt.Color(204, 204, 204));
        dell_mas_ensambladores.setText("+");
        dell_mas_ensambladores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dell_mas_ensambladoresActionPerformed(evt);
            }
        });
        dellWindow.add(dell_mas_ensambladores, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 360, 20, -1));

        dell_cant_ensambladores.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        dell_cant_ensambladores.setForeground(new java.awt.Color(255, 255, 255));
        dell_cant_ensambladores.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dell_cant_ensambladores.setText("0");
        dellWindow.add(dell_cant_ensambladores, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 360, 30, -1));

        dell_menos_ensambladores.setBackground(new java.awt.Color(204, 204, 204));
        dell_menos_ensambladores.setText("-");
        dell_menos_ensambladores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dell_menos_ensambladoresActionPerformed(evt);
            }
        });
        dellWindow.add(dell_menos_ensambladores, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 360, 20, -1));

        jLabel60.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        jLabel60.setForeground(new java.awt.Color(255, 255, 255));
        jLabel60.setText("Ensambladores");
        dellWindow.add(jLabel60, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 330, -1, -1));

        jLabel61.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        jLabel61.setForeground(new java.awt.Color(255, 255, 255));
        jLabel61.setText("Placa Base");
        dellWindow.add(jLabel61, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 510, 200, -1));

        dell_cant_fuentes.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        dell_cant_fuentes.setForeground(new java.awt.Color(255, 255, 255));
        dell_cant_fuentes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dell_cant_fuentes.setText("0");
        dellWindow.add(dell_cant_fuentes, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 230, 30, -1));

        dell_gastosTarjeta.setForeground(new java.awt.Color(255, 255, 255));
        dell_gastosTarjeta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dell_gastosTarjeta.setText("0 $");
        dellWindow.add(dell_gastosTarjeta, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 400, 160, -1));

        maxCPU2.setForeground(new java.awt.Color(255, 255, 255));
        maxCPU2.setText("max. 20");
        dellWindow.add(maxCPU2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 560, 60, -1));

        dell_progressBarCPU.setForeground(new java.awt.Color(255, 255, 255));
        dellWindow.add(dell_progressBarCPU, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 560, 100, 20));

        dell_progressBarRam.setForeground(new java.awt.Color(255, 255, 255));
        dellWindow.add(dell_progressBarRam, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 510, 100, 20));

        maxRAM2.setForeground(new java.awt.Color(255, 255, 255));
        maxRAM2.setText("max. 55");
        dellWindow.add(maxRAM2, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 510, 60, -1));

        dell_progressBarPlaca.setForeground(new java.awt.Color(255, 255, 255));
        dellWindow.add(dell_progressBarPlaca, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 510, 100, 20));

        maxPlaca2.setForeground(new java.awt.Color(255, 255, 255));
        maxPlaca2.setText("max. 25");
        dellWindow.add(maxPlaca2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 510, 60, -1));

        dell_progressBarTarjetas.setForeground(new java.awt.Color(255, 255, 255));
        dellWindow.add(dell_progressBarTarjetas, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 560, 100, 20));

        maxTarjetas2.setForeground(new java.awt.Color(255, 255, 255));
        maxTarjetas2.setText("max. 10");
        dellWindow.add(maxTarjetas2, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 560, 100, -1));

        numGPU.setForeground(new java.awt.Color(255, 255, 255));
        numGPU.setText("0");
        dellWindow.add(numGPU, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 540, 70, -1));

        dell_gastosEnsambladores.setForeground(new java.awt.Color(255, 255, 255));
        dell_gastosEnsambladores.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dell_gastosEnsambladores.setText("0 $");
        dellWindow.add(dell_gastosEnsambladores, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 400, 160, -1));

        dell_gastosRAM.setForeground(new java.awt.Color(255, 255, 255));
        dell_gastosRAM.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dell_gastosRAM.setText("0 $");
        dellWindow.add(dell_gastosRAM, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 270, 140, -1));

        dell_gastosPlaca.setForeground(new java.awt.Color(255, 255, 255));
        dell_gastosPlaca.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dell_gastosPlaca.setText("0 $");
        dellWindow.add(dell_gastosPlaca, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 400, 160, -1));

        jLabel62.setFont(new java.awt.Font("Helvetica Neue", 1, 17)); // NOI18N
        jLabel62.setForeground(new java.awt.Color(255, 255, 255));
        jLabel62.setText("Project Manager");
        dellWindow.add(jLabel62, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 650, -1, -1));

        dell_gastosCPU.setForeground(new java.awt.Color(255, 255, 255));
        dell_gastosCPU.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dell_gastosCPU.setText("0 $");
        dellWindow.add(dell_gastosCPU, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 270, 140, -1));

        jLabel63.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel63.setForeground(new java.awt.Color(255, 255, 255));
        jLabel63.setText("Day Counter");
        dellWindow.add(jLabel63, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 40, -1, -1));

        dell_dayCounter.setFont(new java.awt.Font("Helvetica Neue", 0, 36)); // NOI18N
        dell_dayCounter.setForeground(new java.awt.Color(255, 255, 255));
        dell_dayCounter.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dell_dayCounter.setText("0");
        dellWindow.add(dell_dayCounter, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 80, 90, -1));

        dell_gastosPM.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        dell_gastosPM.setForeground(new java.awt.Color(255, 255, 255));
        dell_gastosPM.setText("0 $");
        dellWindow.add(dell_gastosPM, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 650, 90, -1));

        label11.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        label11.setForeground(new java.awt.Color(255, 255, 255));
        label11.setText("Faltas");
        dellWindow.add(label11, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 650, 50, -1));

        dell_faltasPM.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        dell_faltasPM.setForeground(new java.awt.Color(255, 255, 255));
        dell_faltasPM.setText("0");
        dellWindow.add(dell_faltasPM, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 650, 40, -1));

        dell_gastosDirector.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        dell_gastosDirector.setForeground(new java.awt.Color(255, 255, 255));
        dell_gastosDirector.setText("0 $");
        dellWindow.add(dell_gastosDirector, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 690, 90, -1));

        dell_gastosFuente.setForeground(new java.awt.Color(255, 255, 255));
        dell_gastosFuente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dell_gastosFuente.setText("0 $");
        dellWindow.add(dell_gastosFuente, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 270, 120, -1));

        label12.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        label12.setForeground(new java.awt.Color(255, 255, 255));
        label12.setText("Descontado");
        dellWindow.add(label12, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 650, 90, -1));

        dell_salarioDescontado.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        dell_salarioDescontado.setForeground(new java.awt.Color(255, 255, 255));
        dell_salarioDescontado.setText("0 $");
        dellWindow.add(dell_salarioDescontado, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 650, 80, -1));

        jLabel64.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        jLabel64.setForeground(new java.awt.Color(255, 255, 255));
        jLabel64.setText("Productores de Fuente de Alimentación");
        dellWindow.add(jLabel64, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, 310, -1));

        jSeparator8.setForeground(new java.awt.Color(255, 255, 255));
        dellWindow.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 610, 1100, 20));

        jLabel65.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        jLabel65.setForeground(new java.awt.Color(255, 255, 255));
        jLabel65.setText("Almacenamiento");
        dellWindow.add(jLabel65, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, -1, -1));

        jLabel66.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        jLabel66.setForeground(new java.awt.Color(255, 255, 255));
        jLabel66.setText("Fuente de Alimentación");
        dellWindow.add(jLabel66, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 510, 200, -1));

        jLabel67.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        jLabel67.setForeground(new java.awt.Color(255, 255, 255));
        jLabel67.setText("CPU");
        dellWindow.add(jLabel67, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 560, 200, -1));

        jLabel68.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        jLabel68.setForeground(new java.awt.Color(255, 255, 255));
        jLabel68.setText("RAM");
        dellWindow.add(jLabel68, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 510, 200, -1));

        jLabel69.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        jLabel69.setForeground(new java.awt.Color(255, 255, 255));
        jLabel69.setText("Tarjetas Gráficas");
        dellWindow.add(jLabel69, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 560, 200, -1));

        jSeparator9.setForeground(new java.awt.Color(255, 255, 255));
        dellWindow.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 460, 890, 20));

        dell_statusDir.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        dell_statusDir.setForeground(new java.awt.Color(255, 255, 255));
        dell_statusDir.setText("\"\"");
        dellWindow.add(dell_statusDir, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 690, 70, -1));

        label26.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        label26.setForeground(new java.awt.Color(255, 255, 255));
        label26.setText("Salario");
        dellWindow.add(label26, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 650, 60, -1));

        label27.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        label27.setForeground(new java.awt.Color(255, 255, 255));
        label27.setText("Estatus:");
        dellWindow.add(label27, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 690, 60, -1));

        label28.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        label28.setForeground(new java.awt.Color(255, 255, 255));
        label28.setText("Salario");
        dellWindow.add(label28, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 690, 60, -1));

        label14.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        label14.setForeground(new java.awt.Color(255, 255, 255));
        label14.setText("Estatus:");
        dellWindow.add(label14, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 650, 70, -1));

        dell_statusPM.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        dell_statusPM.setForeground(new java.awt.Color(255, 255, 255));
        dell_statusPM.setText("\"\"");
        dellWindow.add(dell_statusPM, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 650, 70, -1));

        jLabel70.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel70.setForeground(new java.awt.Color(255, 255, 255));
        jLabel70.setText("Vendidas");
        dellWindow.add(jLabel70, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 50, 100, -1));

        dell_compVendidas.setFont(new java.awt.Font("Helvetica Neue", 0, 36)); // NOI18N
        dell_compVendidas.setForeground(new java.awt.Color(255, 255, 255));
        dell_compVendidas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dell_compVendidas.setText("0");
        dellWindow.add(dell_compVendidas, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 80, 150, -1));

        dell_compTarjeta.setFont(new java.awt.Font("Helvetica Neue", 0, 36)); // NOI18N
        dell_compTarjeta.setForeground(new java.awt.Color(255, 255, 255));
        dell_compTarjeta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dell_compTarjeta.setText("0");
        dellWindow.add(dell_compTarjeta, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 80, 130, -1));

        jLabel71.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel71.setForeground(new java.awt.Color(255, 255, 255));
        jLabel71.setText("Computadoras");
        dellWindow.add(jLabel71, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 30, 140, -1));

        jLabel72.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel72.setForeground(new java.awt.Color(255, 255, 255));
        jLabel72.setText("Computadoras");
        dellWindow.add(jLabel72, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 30, 140, -1));

        jLabel73.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel73.setForeground(new java.awt.Color(255, 255, 255));
        jLabel73.setText("Tarjeta Gráfica");
        dellWindow.add(jLabel73, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 50, 140, -1));

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Media/Dell Logo.png"))); // NOI18N
        dellWindow.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 130, 120));

        maxFuente3.setForeground(new java.awt.Color(255, 255, 255));
        maxFuente3.setText("max. 35");
        dellWindow.add(maxFuente3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 510, 70, -1));

        numFuentes.setForeground(new java.awt.Color(255, 255, 255));
        numFuentes.setText("0");
        dellWindow.add(numFuentes, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 490, 70, -1));

        numCPU.setForeground(new java.awt.Color(255, 255, 255));
        numCPU.setText("0");
        dellWindow.add(numCPU, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 540, 70, -1));

        numPlaca.setForeground(new java.awt.Color(255, 255, 255));
        numPlaca.setText("0");
        dellWindow.add(numPlaca, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 490, 70, -1));

        numRAM.setForeground(new java.awt.Color(255, 255, 255));
        numRAM.setText("0");
        dellWindow.add(numRAM, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 490, 70, -1));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dellWindow, javax.swing.GroupLayout.DEFAULT_SIZE, 1226, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(dellWindow, javax.swing.GroupLayout.PREFERRED_SIZE, 782, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1226, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 782, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void dell_ver_graficoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dell_ver_graficoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dell_ver_graficoActionPerformed

    private void dell_menos_fuentesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dell_menos_fuentesActionPerformed
        // TODO add your handling code here:
        getDell().fireEmployee(WorkerTypes.PowerSupplyProducer.getId());
        this.getDell_cant_fuentes().setText(Integer.toString(getDell().getEmployees()[WorkerTypes.PowerSupplyProducer.getId()].getSize()));
        
    }//GEN-LAST:event_dell_menos_fuentesActionPerformed

    private void dell_mas_fuentesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dell_mas_fuentesActionPerformed
        // TODO add your handling code here:
        getDell().hireEmployee(WorkerTypes.PowerSupplyProducer.getId());
        this.getDell_cant_fuentes().setText(Integer.toString(getDell().getEmployees()[WorkerTypes.PowerSupplyProducer.getId()].getSize()));
        
    }//GEN-LAST:event_dell_mas_fuentesActionPerformed

    private void dell_inicio_simulacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dell_inicio_simulacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dell_inicio_simulacionActionPerformed

    private void dell_menos_cpuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dell_menos_cpuActionPerformed
        // TODO add your handling code here:
        getDell().fireEmployee(WorkerTypes.CpuProducer.getId());
        this.getDell_cant_cpu().setText(Integer.toString(getDell().getEmployees()[WorkerTypes.CpuProducer.getId()].getSize()));
        
    }//GEN-LAST:event_dell_menos_cpuActionPerformed

    private void dell_mas_cpuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dell_mas_cpuActionPerformed
        // TODO add your handling code here:
        getDell().hireEmployee(WorkerTypes.CpuProducer.getId());
        this.getDell_cant_cpu().setText(Integer.toString(getDell().getEmployees()[WorkerTypes.CpuProducer.getId()].getSize()));
        
    }//GEN-LAST:event_dell_mas_cpuActionPerformed

    private void dell_menos_ramActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dell_menos_ramActionPerformed
        // TODO add your handling code here:
        getDell().fireEmployee(WorkerTypes.RamProducer.getId());
        this.getDell_cant_ram().setText(Integer.toString(getDell().getEmployees()[WorkerTypes.RamProducer.getId()].getSize()));
        
    }//GEN-LAST:event_dell_menos_ramActionPerformed

    private void dell_mas_ramActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dell_mas_ramActionPerformed
        // TODO add your handling code here:
        getDell().hireEmployee(WorkerTypes.RamProducer.getId());
        this.getDell_cant_ram().setText(Integer.toString(getDell().getEmployees()[WorkerTypes.RamProducer.getId()].getSize()));
    }//GEN-LAST:event_dell_mas_ramActionPerformed

    private void dell_menos_tarjetasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dell_menos_tarjetasActionPerformed
        // TODO add your handling code here:
        getDell().fireEmployee(WorkerTypes.GpuProducer.getId());
        this.getDell_cant_tarjetas().setText(Integer.toString(getDell().getEmployees()[WorkerTypes.GpuProducer.getId()].getSize()));
        
    }//GEN-LAST:event_dell_menos_tarjetasActionPerformed

    private void dell_menos_placaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dell_menos_placaActionPerformed
        // TODO add your handling code here:
        getDell().fireEmployee(WorkerTypes.MotherboardProducer.getId());
        this.getDell_cant_placa().setText(Integer.toString(getDell().getEmployees()[WorkerTypes.MotherboardProducer.getId()].getSize()));
        
    }//GEN-LAST:event_dell_menos_placaActionPerformed

    private void dell_menos_ensambladoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dell_menos_ensambladoresActionPerformed
        // TODO add your handling code here:
        getDell().fireEmployee(WorkerTypes.Assembler.getId());
        this.getDell_cant_ensambladores().setText(Integer.toString(getDell().getEmployees()[WorkerTypes.Assembler.getId()].getSize()));
        
    }//GEN-LAST:event_dell_menos_ensambladoresActionPerformed

    private void dell_mas_tarjetasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dell_mas_tarjetasActionPerformed
        // TODO add your handling code here:
        getDell().hireEmployee(WorkerTypes.GpuProducer.getId());
        this.getDell_cant_tarjetas().setText(Integer.toString(getDell().getEmployees()[WorkerTypes.GpuProducer.getId()].getSize()));
    }//GEN-LAST:event_dell_mas_tarjetasActionPerformed

    private void dell_mas_placaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dell_mas_placaActionPerformed
        // TODO add your handling code here:
        getDell().hireEmployee(WorkerTypes.MotherboardProducer.getId());
        this.getDell_cant_placa().setText(Integer.toString(getDell().getEmployees()[WorkerTypes.MotherboardProducer.getId()].getSize()));
    }//GEN-LAST:event_dell_mas_placaActionPerformed

    private void dell_mas_ensambladoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dell_mas_ensambladoresActionPerformed
        // TODO add your handling code here:
        getDell().hireEmployee(WorkerTypes.Assembler.getId());
        this.getDell_cant_ensambladores().setText(Integer.toString(getDell().getEmployees()[WorkerTypes.Assembler.getId()].getSize()));
    }//GEN-LAST:event_dell_mas_ensambladoresActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel dellWindow;
    private javax.swing.JLabel dell_cant_cpu;
    private javax.swing.JLabel dell_cant_ensambladores;
    private javax.swing.JLabel dell_cant_fuentes;
    private javax.swing.JLabel dell_cant_placa;
    private javax.swing.JLabel dell_cant_ram;
    private javax.swing.JLabel dell_cant_tarjetas;
    private javax.swing.JLabel dell_compTarjeta;
    private javax.swing.JLabel dell_compVendidas;
    private javax.swing.JLabel dell_dayCounter;
    private javax.swing.JLabel dell_faltasPM;
    private javax.swing.JLabel dell_gastosCPU;
    private javax.swing.JLabel dell_gastosDirector;
    private javax.swing.JLabel dell_gastosEnsambladores;
    private javax.swing.JLabel dell_gastosFuente;
    private javax.swing.JLabel dell_gastosPM;
    private javax.swing.JLabel dell_gastosPlaca;
    private javax.swing.JLabel dell_gastosRAM;
    private javax.swing.JLabel dell_gastosTarjeta;
    private javax.swing.JButton dell_inicio_simulacion;
    private javax.swing.JButton dell_mas_cpu;
    private javax.swing.JButton dell_mas_ensambladores;
    private javax.swing.JButton dell_mas_fuentes;
    private javax.swing.JButton dell_mas_placa;
    private javax.swing.JButton dell_mas_ram;
    private javax.swing.JButton dell_mas_tarjetas;
    private javax.swing.JButton dell_menos_cpu;
    private javax.swing.JButton dell_menos_ensambladores;
    private javax.swing.JButton dell_menos_fuentes;
    private javax.swing.JButton dell_menos_placa;
    private javax.swing.JButton dell_menos_ram;
    private javax.swing.JButton dell_menos_tarjetas;
    private javax.swing.JLabel dell_netProfit;
    private javax.swing.JProgressBar dell_progressBarCPU;
    private javax.swing.JProgressBar dell_progressBarFuente;
    private javax.swing.JProgressBar dell_progressBarPlaca;
    private javax.swing.JProgressBar dell_progressBarRam;
    private javax.swing.JProgressBar dell_progressBarTarjetas;
    private javax.swing.JLabel dell_salarioDescontado;
    private javax.swing.JLabel dell_statusDir;
    private javax.swing.JLabel dell_statusPM;
    private javax.swing.JLabel dell_totalCost;
    private javax.swing.JLabel dell_totalEarnings;
    private javax.swing.JButton dell_ver_grafico;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JLabel label11;
    private javax.swing.JLabel label12;
    private javax.swing.JLabel label14;
    private javax.swing.JLabel label26;
    private javax.swing.JLabel label27;
    private javax.swing.JLabel label28;
    private javax.swing.JLabel maxCPU2;
    private javax.swing.JLabel maxFuente3;
    private javax.swing.JLabel maxPlaca2;
    private javax.swing.JLabel maxRAM2;
    private javax.swing.JLabel maxTarjetas2;
    private javax.swing.JLabel numCPU;
    private javax.swing.JLabel numFuentes;
    private javax.swing.JLabel numGPU;
    private javax.swing.JLabel numPlaca;
    private javax.swing.JLabel numRAM;
    // End of variables declaration//GEN-END:variables

    public Company getDell() {
        return Dell;
    }

    public void setDell(Company Dell) {
        this.Dell = Dell;
    }

    public JPanel getDellWindow() {
        return dellWindow;
    }

    public void setDellWindow(JPanel dellWindow) {
        this.dellWindow = dellWindow;
    }

    public JLabel getDell_cant_cpu() {
        return dell_cant_cpu;
    }

    public void setDell_cant_cpu(JLabel dell_cant_cpu) {
        this.dell_cant_cpu = dell_cant_cpu;
    }

    public JLabel getDell_cant_ensambladores() {
        return dell_cant_ensambladores;
    }

    public void setDell_cant_ensambladores(JLabel dell_cant_ensambladores) {
        this.dell_cant_ensambladores = dell_cant_ensambladores;
    }

    public JLabel getDell_cant_fuentes() {
        return dell_cant_fuentes;
    }

    public void setDell_cant_fuentes(JLabel dell_cant_fuentes) {
        this.dell_cant_fuentes = dell_cant_fuentes;
    }

    public JLabel getDell_cant_placa() {
        return dell_cant_placa;
    }

    public void setDell_cant_placa(JLabel dell_cant_placa) {
        this.dell_cant_placa = dell_cant_placa;
    }

    public JLabel getDell_cant_ram() {
        return dell_cant_ram;
    }

    public void setDell_cant_ram(JLabel dell_cant_ram) {
        this.dell_cant_ram = dell_cant_ram;
    }

    public JLabel getDell_cant_tarjetas() {
        return dell_cant_tarjetas;
    }

    public void setDell_cant_tarjetas(JLabel dell_cant_tarjetas) {
        this.dell_cant_tarjetas = dell_cant_tarjetas;
    }

    public JLabel getDell_compTarjeta() {
        return dell_compTarjeta;
    }

    public void setDell_compTarjeta(JLabel dell_compTarjeta) {
        this.dell_compTarjeta = dell_compTarjeta;
    }

    public JLabel getDell_compVendidas() {
        return dell_compVendidas;
    }

    public void setDell_compVendidas(JLabel dell_compVendidas) {
        this.dell_compVendidas = dell_compVendidas;
    }

    public JLabel getDell_dayCounter() {
        return dell_dayCounter;
    }

    public void setDell_dayCounter(JLabel dell_dayCounter) {
        this.dell_dayCounter = dell_dayCounter;
    }

    public JLabel getDell_faltasPM() {
        return dell_faltasPM;
    }

    public void setDell_faltasPM(JLabel dell_faltasPM) {
        this.dell_faltasPM = dell_faltasPM;
    }

    public JLabel getDell_gastosCPU() {
        return dell_gastosCPU;
    }

    public void setDell_gastosCPU(JLabel dell_gastosCPU) {
        this.dell_gastosCPU = dell_gastosCPU;
    }

    public JLabel getDell_gastosDirector() {
        return dell_gastosDirector;
    }

    public void setDell_gastosDirector(JLabel dell_gastosDirector) {
        this.dell_gastosDirector = dell_gastosDirector;
    }

    public JLabel getDell_gastosEnsambladores() {
        return dell_gastosEnsambladores;
    }

    public void setDell_gastosEnsambladores(JLabel dell_gastosEnsambladores) {
        this.dell_gastosEnsambladores = dell_gastosEnsambladores;
    }

    public JLabel getDell_gastosFuente() {
        return dell_gastosFuente;
    }

    public void setDell_gastosFuente(JLabel dell_gastosFuente) {
        this.dell_gastosFuente = dell_gastosFuente;
    }

    public JLabel getDell_gastosPM() {
        return dell_gastosPM;
    }

    public void setDell_gastosPM(JLabel dell_gastosPM) {
        this.dell_gastosPM = dell_gastosPM;
    }

    public JLabel getDell_gastosPlaca() {
        return dell_gastosPlaca;
    }

    public void setDell_gastosPlaca(JLabel dell_gastosPlaca) {
        this.dell_gastosPlaca = dell_gastosPlaca;
    }

    public JLabel getDell_gastosRAM() {
        return dell_gastosRAM;
    }

    public void setDell_gastosRAM(JLabel dell_gastosRAM) {
        this.dell_gastosRAM = dell_gastosRAM;
    }

    public JLabel getDell_gastosTarjeta() {
        return dell_gastosTarjeta;
    }

    public void setDell_gastosTarjeta(JLabel dell_gastosTarjeta) {
        this.dell_gastosTarjeta = dell_gastosTarjeta;
    }

    public JButton getDell_inicio_simulacion() {
        return dell_inicio_simulacion;
    }

    public void setDell_inicio_simulacion(JButton dell_inicio_simulacion) {
        this.dell_inicio_simulacion = dell_inicio_simulacion;
    }

    public JButton getDell_mas_cpu() {
        return dell_mas_cpu;
    }

    public void setDell_mas_cpu(JButton dell_mas_cpu) {
        this.dell_mas_cpu = dell_mas_cpu;
    }

    public JButton getDell_mas_ensambladores() {
        return dell_mas_ensambladores;
    }

    public void setDell_mas_ensambladores(JButton dell_mas_ensambladores) {
        this.dell_mas_ensambladores = dell_mas_ensambladores;
    }

    public JButton getDell_mas_fuentes() {
        return dell_mas_fuentes;
    }

    public void setDell_mas_fuentes(JButton dell_mas_fuentes) {
        this.dell_mas_fuentes = dell_mas_fuentes;
    }

    public JButton getDell_mas_placa() {
        return dell_mas_placa;
    }

    public void setDell_mas_placa(JButton dell_mas_placa) {
        this.dell_mas_placa = dell_mas_placa;
    }

    public JButton getDell_mas_ram() {
        return dell_mas_ram;
    }

    public void setDell_mas_ram(JButton dell_mas_ram) {
        this.dell_mas_ram = dell_mas_ram;
    }

    public JButton getDell_mas_tarjetas() {
        return dell_mas_tarjetas;
    }

    public void setDell_mas_tarjetas(JButton dell_mas_tarjetas) {
        this.dell_mas_tarjetas = dell_mas_tarjetas;
    }

    public JButton getDell_menos_cpu() {
        return dell_menos_cpu;
    }

    public void setDell_menos_cpu(JButton dell_menos_cpu) {
        this.dell_menos_cpu = dell_menos_cpu;
    }

    public JButton getDell_menos_ensambladores() {
        return dell_menos_ensambladores;
    }

    public void setDell_menos_ensambladores(JButton dell_menos_ensambladores) {
        this.dell_menos_ensambladores = dell_menos_ensambladores;
    }

    public JButton getDell_menos_fuentes() {
        return dell_menos_fuentes;
    }

    public void setDell_menos_fuentes(JButton dell_menos_fuentes) {
        this.dell_menos_fuentes = dell_menos_fuentes;
    }

    public JButton getDell_menos_placa() {
        return dell_menos_placa;
    }

    public void setDell_menos_placa(JButton dell_menos_placa) {
        this.dell_menos_placa = dell_menos_placa;
    }

    public JButton getDell_menos_ram() {
        return dell_menos_ram;
    }

    public void setDell_menos_ram(JButton dell_menos_ram) {
        this.dell_menos_ram = dell_menos_ram;
    }

    public JButton getDell_menos_tarjetas() {
        return dell_menos_tarjetas;
    }

    public void setDell_menos_tarjetas(JButton dell_menos_tarjetas) {
        this.dell_menos_tarjetas = dell_menos_tarjetas;
    }

    public JLabel getDell_netProfit() {
        return dell_netProfit;
    }

    public void setDell_netProfit(JLabel dell_netProfit) {
        this.dell_netProfit = dell_netProfit;
    }

    public JProgressBar getDell_progressBarCPU() {
        return dell_progressBarCPU;
    }

    public void setDell_progressBarCPU(JProgressBar dell_progressBarCPU) {
        this.dell_progressBarCPU = dell_progressBarCPU;
    }

    public JProgressBar getDell_progressBarFuente() {
        return dell_progressBarFuente;
    }

    public void setDell_progressBarFuente(JProgressBar dell_progressBarFuente) {
        this.dell_progressBarFuente = dell_progressBarFuente;
    }

    public JProgressBar getDell_progressBarPlaca() {
        return dell_progressBarPlaca;
    }

    public void setDell_progressBarPlaca(JProgressBar dell_progressBarPlaca) {
        this.dell_progressBarPlaca = dell_progressBarPlaca;
    }

    public JProgressBar getDell_progressBarRam() {
        return dell_progressBarRam;
    }

    public void setDell_progressBarRam(JProgressBar dell_progressBarRam) {
        this.dell_progressBarRam = dell_progressBarRam;
    }

    public JProgressBar getDell_progressBarTarjetas() {
        return dell_progressBarTarjetas;
    }

    public void setDell_progressBarTarjetas(JProgressBar dell_progressBarTarjetas) {
        this.dell_progressBarTarjetas = dell_progressBarTarjetas;
    }

    public JLabel getDell_salarioDescontado() {
        return dell_salarioDescontado;
    }

    public void setDell_salarioDescontado(JLabel dell_salarioDescontado) {
        this.dell_salarioDescontado = dell_salarioDescontado;
    }

    public JLabel getDell_statusDir() {
        return dell_statusDir;
    }

    public void setDell_statusDir(JLabel dell_statusDir) {
        this.dell_statusDir = dell_statusDir;
    }

    public JLabel getDell_statusPM() {
        return dell_statusPM;
    }

    public void setDell_statusPM(JLabel dell_statusPM) {
        this.dell_statusPM = dell_statusPM;
    }

    public JLabel getDell_totalCost() {
        return dell_totalCost;
    }

    public void setDell_totalCost(JLabel dell_totalCost) {
        this.dell_totalCost = dell_totalCost;
    }

    public JLabel getDell_totalEarnings() {
        return dell_totalEarnings;
    }

    public void setDell_totalEarnings(JLabel dell_totalEarnings) {
        this.dell_totalEarnings = dell_totalEarnings;
    }

    public JButton getDell_ver_grafico() {
        return dell_ver_grafico;
    }

    public void setDell_ver_grafico(JButton dell_ver_grafico) {
        this.dell_ver_grafico = dell_ver_grafico;
    }

    public JLabel getMaxCPU2() {
        return maxCPU2;
    }

    public void setMaxCPU2(JLabel maxCPU2) {
        this.maxCPU2 = maxCPU2;
    }

    public JLabel getMaxFuente2() {
        return numGPU;
    }

    public void setMaxFuente2(JLabel maxFuente2) {
        this.numGPU = maxFuente2;
    }

    public JLabel getMaxPlaca2() {
        return maxPlaca2;
    }

    public void setMaxPlaca2(JLabel maxPlaca2) {
        this.maxPlaca2 = maxPlaca2;
    }

    public JLabel getMaxRAM2() {
        return maxRAM2;
    }

    public void setMaxRAM2(JLabel maxRAM2) {
        this.maxRAM2 = maxRAM2;
    }

    public JLabel getMaxTarjetas2() {
        return maxTarjetas2;
    }

    public void setMaxTarjetas2(JLabel maxTarjetas2) {
        this.maxTarjetas2 = maxTarjetas2;
    }

    public JLabel getNumCPU() {
        return numCPU;
    }

    public void setNumCPU(JLabel numCPU) {
        this.numCPU = numCPU;
    }

    public JLabel getNumFuentes() {
        return numFuentes;
    }

    public void setNumFuentes(JLabel numFuentes) {
        this.numFuentes = numFuentes;
    }

    public JLabel getNumGPU() {
        return numGPU;
    }

    public void setNumGPU(JLabel numGPU) {
        this.numGPU = numGPU;
    }

    public JLabel getNumPlaca() {
        return numPlaca;
    }

    public void setNumPlaca(JLabel numPlaca) {
        this.numPlaca = numPlaca;
    }

    public JLabel getNumRAM() {
        return numRAM;
    }

    public void setNumRAM(JLabel numRAM) {
        this.numRAM = numRAM;
    }
    
    
    

}
