/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;
        
import Companies.Company;
import Interfaz.DrawGraph;
import Main.CommonVariables;
import javax.swing.JOptionPane;

/**
 *
 * @author ani
 */
public class MainMenu extends javax.swing.JFrame {
    
    private Company apple;
    private Company dell;
    
    private boolean appleStarted;
    private boolean dellStarted;

    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        initComponents();
        this.jTabbedPane1.addTab("Ajustes", new SettingsTab());
        this.appleStarted = false;
        this.dellStarted = false;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        seeGraphs = new javax.swing.JButton();
        startApple = new javax.swing.JButton();
        startDell = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 0, 102));

        jTabbedPane1.setForeground(new java.awt.Color(102, 0, 102));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        seeGraphs.setBackground(new java.awt.Color(102, 0, 102));
        seeGraphs.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        seeGraphs.setForeground(new java.awt.Color(255, 255, 255));
        seeGraphs.setText("Ver Gráficos");
        seeGraphs.setBorderPainted(false);
        seeGraphs.setOpaque(true);
        seeGraphs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seeGraphsActionPerformed(evt);
            }
        });
        jPanel1.add(seeGraphs, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 640, 240, 40));

        startApple.setBackground(new java.awt.Color(153, 153, 153));
        startApple.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        startApple.setForeground(new java.awt.Color(255, 255, 255));
        startApple.setText("Iniciar Apple");
        startApple.setBorderPainted(false);
        startApple.setOpaque(true);
        startApple.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startAppleActionPerformed(evt);
            }
        });
        jPanel1.add(startApple, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 520, 240, 40));

        startDell.setBackground(new java.awt.Color(153, 153, 153));
        startDell.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        startDell.setForeground(new java.awt.Color(255, 255, 255));
        startDell.setText("Iniciar Dell");
        startDell.setBorderPainted(false);
        startDell.setOpaque(true);
        startDell.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startDellActionPerformed(evt);
            }
        });
        jPanel1.add(startDell, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 580, 240, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Media/Main Menu.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jTabbedPane1.addTab("Menú Principal", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1226, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void startAppleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startAppleActionPerformed
        // TODO add your handling code here:
        if (!isAppleStarted()) {
            StartSimulation.startSimApple();
            setAppleStarted(true);
            this.startApple.setText("Detener Apple");
        }else{
            for (int i = 0; i < CommonVariables.getMainMenu().getTabPanel().getTabCount(); i++) {
                if(CommonVariables.getMainMenu().getTabPanel().getTitleAt(i).equals("Apple")){
                    StartSimulation.stopApple();
                    CommonVariables.getMainMenu().getTabPanel().remove(i);
                    break;
                }
            }
            
            setAppleStarted(false);
            this.startApple.setText("Iniciar Apple");
        }
    }//GEN-LAST:event_startAppleActionPerformed

    private void startDellActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startDellActionPerformed
        // TODO add your handling code here:
        if (!isDellStarted()) {
            StartSimulation.startSimDell();
            setDellStarted(true);
            this.startDell.setText("Detener Dell");
        }else{
            for (int i = 0; i < CommonVariables.getMainMenu().getTabPanel().getTabCount(); i++) {
                if(CommonVariables.getMainMenu().getTabPanel().getTitleAt(i).equals("Dell")){
                    StartSimulation.stopDell();
                    CommonVariables.getMainMenu().getTabPanel().remove(i);
                    break;
                }
            }
            
            setDellStarted(false);
            this.startDell.setText("Iniciar Dell");
        }
    }//GEN-LAST:event_startDellActionPerformed

    private void seeGraphsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seeGraphsActionPerformed
        if (appleStarted && dellStarted){
            
            DrawGraph chartBoth = new DrawGraph(CommonVariables.getApple(), 3, CommonVariables.getDell());
       
        } else {
            JOptionPane.showMessageDialog(null, " ¡Recuerda iniciar ambas simulaciones!" );
        }     }//GEN-LAST:event_seeGraphsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton seeGraphs;
    private javax.swing.JButton startApple;
    private javax.swing.JButton startDell;
    // End of variables declaration//GEN-END:variables
    
       /**
     * @return the tabPanel
     */
    public javax.swing.JTabbedPane getTabPanel() {
        return jTabbedPane1;
    }

    /**
     * @param tabPanel the tabPanel to set
     */
    public void setTabPanel(javax.swing.JTabbedPane jTabbedPane1) {
        this.jTabbedPane1 = jTabbedPane1;
    }

    public Company getApple() {
        return apple;
    }

    public void setApple(Company apple) {
        this.apple = apple;
    }

    public Company getDell() {
        return dell;
    }

    public void setDell(Company dell) {
        this.dell = dell;
    }

    public boolean isAppleStarted() {
        return appleStarted;
    }

    public void setAppleStarted(boolean appleStarted) {
        this.appleStarted = appleStarted;
    }

    public boolean isDellStarted() {
        return dellStarted;
    }

    public void setDellStarted(boolean dellStarted) {
        this.dellStarted = dellStarted;
    }
    
    
    
}
