/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Interfaz;

import Companies.CompanyType;
import Disk.FileReader;
import Disk.FileReader.JSONFile;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;

/**
 *
 * @author ani
 */
public class SettingsTab extends javax.swing.JPanel {
    
    JSONFile file;

    /**
     * Creates new form SettingsTab
     */
    public SettingsTab() {
        initComponents();
        updateData();
        ajustes_compañia.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                updateData();
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        settingsWindow = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        ajustes_compañia = new javax.swing.JComboBox<>();
        jLabel28 = new javax.swing.JLabel();
        ajustes_entrega = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        ajustes_ensam = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        ajustes_dias_eq1 = new javax.swing.JTextField();
        ajustes_fuentes = new javax.swing.JTextField();
        ajustes_tarjetas = new javax.swing.JTextField();
        ajustes_cpu = new javax.swing.JTextField();
        ajustes_placa = new javax.swing.JTextField();
        ajustes_RAM = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel30 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();

        settingsWindow.setBackground(new java.awt.Color(210, 174, 246));
        settingsWindow.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel27.setFont(new java.awt.Font("Helvetica Neue", 1, 36)); // NOI18N
        jLabel27.setText("Ajustes de Simulación");
        settingsWindow.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 30, -1, -1));

        ajustes_compañia.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        ajustes_compañia.setForeground(new java.awt.Color(153, 0, 204));
        ajustes_compañia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dell", "Apple" }));
        settingsWindow.add(ajustes_compañia, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 110, 300, 40));

        jLabel28.setFont(new java.awt.Font("Helvetica Neue", 1, 20)); // NOI18N
        jLabel28.setText("Número Incial de Trabajadores");
        settingsWindow.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, -1, -1));

        ajustes_entrega.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajustes_entregaActionPerformed(evt);
            }
        });
        settingsWindow.add(ajustes_entrega, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 220, 80, 30));

        jLabel29.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel29.setText("Compañía");
        settingsWindow.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 120, -1, -1));

        ajustes_ensam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajustes_ensamActionPerformed(evt);
            }
        });
        settingsWindow.add(ajustes_ensam, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 550, 80, 30));

        jSeparator4.setForeground(new java.awt.Color(102, 0, 102));
        settingsWindow.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, 1080, 20));

        jLabel31.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel31.setText("Días para la entrega de computadoras");
        settingsWindow.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 220, -1, -1));

        jLabel32.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel32.setText("Productores de Fuente de Alimentación");
        settingsWindow.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 420, 360, -1));

        jLabel33.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel33.setText("Productores de Tarjetas Gráficas");
        settingsWindow.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 490, 350, -1));

        jLabel34.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel34.setText("Productores de Placa Base");
        settingsWindow.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 420, 270, -1));

        jLabel35.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel35.setText("Productores de CPU");
        settingsWindow.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 550, 220, -1));

        jLabel36.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel36.setText("Productores de RAM");
        settingsWindow.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 490, 220, -1));

        jLabel37.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel37.setText("Ensambladores");
        settingsWindow.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 550, 180, -1));

        ajustes_dias_eq1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajustes_dias_eq1ActionPerformed(evt);
            }
        });
        settingsWindow.add(ajustes_dias_eq1, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 170, 80, 30));

        ajustes_fuentes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajustes_fuentesActionPerformed(evt);
            }
        });
        settingsWindow.add(ajustes_fuentes, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 420, 80, 30));

        ajustes_tarjetas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajustes_tarjetasActionPerformed(evt);
            }
        });
        settingsWindow.add(ajustes_tarjetas, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 490, 80, 30));

        ajustes_cpu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajustes_cpuActionPerformed(evt);
            }
        });
        settingsWindow.add(ajustes_cpu, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 550, 80, 30));

        ajustes_placa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajustes_placaActionPerformed(evt);
            }
        });
        settingsWindow.add(ajustes_placa, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 420, 80, 30));

        ajustes_RAM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajustes_RAMActionPerformed(evt);
            }
        });
        settingsWindow.add(ajustes_RAM, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 490, 80, 30));

        jButton1.setBackground(new java.awt.Color(102, 0, 102));
        jButton1.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(102, 0, 102));
        jButton1.setText("Guardar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        settingsWindow.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 640, 440, 40));

        jLabel30.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel30.setText("Equivalente a un día en segundos ");
        settingsWindow.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 170, -1, -1));

        jLabel38.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Media/settings-gears (1).png"))); // NOI18N
        settingsWindow.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 110, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1226, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(settingsWindow, javax.swing.GroupLayout.PREFERRED_SIZE, 1226, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 782, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(settingsWindow, javax.swing.GroupLayout.PREFERRED_SIZE, 782, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ajustes_entregaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajustes_entregaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ajustes_entregaActionPerformed

    private void ajustes_ensamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajustes_ensamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ajustes_ensamActionPerformed

    private void ajustes_dias_eq1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajustes_dias_eq1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ajustes_dias_eq1ActionPerformed

    private void ajustes_fuentesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajustes_fuentesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ajustes_fuentesActionPerformed

    private void ajustes_tarjetasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajustes_tarjetasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ajustes_tarjetasActionPerformed

    private void ajustes_cpuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajustes_cpuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ajustes_cpuActionPerformed

    private void ajustes_placaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajustes_placaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ajustes_placaActionPerformed

    private void ajustes_RAMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajustes_RAMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ajustes_RAMActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try {

            String compName = (String) this.ajustes_compañia.getSelectedItem();

            CompanyType compId = null;
            switch (compName) {
                case "Nickelodeon":
                    compId = CompanyType.Apple;
                    break;
                case "Disney":
                    compId = CompanyType.Dell;
                    break;
                default:
                    break;
            }

            int numMotherboard = Integer.parseInt(this.ajustes_placa.getText().trim());
            int numCPU = Integer.parseInt(this.ajustes_cpu.getText().trim());
            int numPowerSupply = Integer.parseInt(this.ajustes_fuentes.getText().trim());
            int numRAM = Integer.parseInt(this.ajustes_RAM.getText().trim());
            int numGPU = Integer.parseInt(this.ajustes_tarjetas.getText().trim());
            int numAssembler = Integer.parseInt(this.ajustes_ensam.getText().trim());
            int dayLength = Integer.parseInt(this.ajustes_dias_eq1.getText().trim());
            int daysBetweenReleases = Integer.parseInt(this.ajustes_entrega.getText().trim());

            int sum = numMotherboard + numCPU + numPowerSupply + numRAM + numGPU + numAssembler;
            boolean canDo = checkSum(compId, sum);

            FileReader fileAdm = new FileReader();
            FileReader.JSONFile fileToSave = fileAdm.new JSONFile();

            if (numMotherboard > 0 && numCPU > 0 && numPowerSupply > 0 && numRAM > 0 && numGPU > 0 && numAssembler > 0 && dayLength > 0 && daysBetweenReleases > 0 && canDo) {
                fileToSave.setDayLength(dayLength);
                fileToSave.setDaysBetweenReleases(daysBetweenReleases);
                fileToSave.setNumMotherboardProducer(numMotherboard);
                fileToSave.setNumCpuProducer(numCPU);
                fileToSave.setNumRamProducer(numRAM);
                fileToSave.setNumPowerSupplyProducer(numPowerSupply);
                fileToSave.setNumGpuProducer(numGPU);
                fileToSave.setNumAssemblers(numAssembler);

                fileAdm.saveFile(compId, fileToSave);
                JOptionPane.showMessageDialog(null, "¡Se han guardado los valores correctamente!");

                setToZero();
            } else {
                JOptionPane.showMessageDialog(null, "Por favor ingrese valores válidos acorde a los requerimientos de la empresa");
                setToZero();
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Ingrese valores válidos");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    public void setToZero() {
        this.ajustes_dias_eq1.setText("");
        this.ajustes_entrega.setText("");
        this.ajustes_placa.setText("");
        this.ajustes_cpu.setText("");
        this.ajustes_RAM.setText("");
        this.ajustes_fuentes.setText("");
        this.ajustes_tarjetas.setText("");
        this.ajustes_ensam.setText("");
    }

    public boolean checkSum(CompanyType compID, int sum) {
        switch (compID) {
            case Apple:
                int max1 = 15;
                return (sum <= max1);
            case Dell:
                int max2 = 18;
                return sum <= max2;
        }
        return false;

    }

    public void updateData() {
        FileReader fileAdmin = new FileReader();
        if (ajustes_compañia.getSelectedItem() == "Apple") {
            file = fileAdmin.getFile(CompanyType.Apple);
            this.ajustes_dias_eq1.setText(String.valueOf(file.getDayLength()));
            this.ajustes_entrega.setText(String.valueOf(file.getDaysBetweenReleases()));
            this.ajustes_placa.setText(String.valueOf(file.getNumMotherboardProducer()));
            this.ajustes_cpu.setText(String.valueOf(file.getNumCpuProducer()));
            this.ajustes_RAM.setText(String.valueOf(file.getNumRamProducer()));
            this.ajustes_fuentes.setText(String.valueOf(file.getNumPowerSupplyProducer()));
            this.ajustes_tarjetas.setText(String.valueOf(file.getNumGpuProducer()));
            this.ajustes_ensam.setText(String.valueOf(file.getNumAssemblers()));
        } else {
            file = fileAdmin.getFile(CompanyType.Dell);
            this.ajustes_dias_eq1.setText(String.valueOf(file.getDayLength()));
            this.ajustes_entrega.setText(String.valueOf(file.getDaysBetweenReleases()));
            this.ajustes_placa.setText(String.valueOf(file.getNumMotherboardProducer()));
            this.ajustes_cpu.setText(String.valueOf(file.getNumCpuProducer()));
            this.ajustes_RAM.setText(String.valueOf(file.getNumRamProducer()));
            this.ajustes_fuentes.setText(String.valueOf(file.getNumPowerSupplyProducer()));
            this.ajustes_tarjetas.setText(String.valueOf(file.getNumGpuProducer()));
            this.ajustes_ensam.setText(String.valueOf(file.getNumAssemblers()));
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ajustes_RAM;
    private javax.swing.JComboBox<String> ajustes_compañia;
    private javax.swing.JTextField ajustes_cpu;
    private javax.swing.JTextField ajustes_dias_eq1;
    private javax.swing.JTextField ajustes_ensam;
    private javax.swing.JTextField ajustes_entrega;
    private javax.swing.JTextField ajustes_fuentes;
    private javax.swing.JTextField ajustes_placa;
    private javax.swing.JTextField ajustes_tarjetas;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JPanel settingsWindow;
    // End of variables declaration//GEN-END:variables
}
